version: '3.8'

services:
  # Contenedor de la Base de Datos (MariaDB)
  base-datos:
    image: mariadb:11.4
    container_name: mariadb_api
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: Anubis@68
      MARIADB_DATABASE: techstore
      MARIADB_USER: root
      MARIADB_PASSWORD: Anubis@68
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql # Tus datos se guardan de forma segura aquí

  # Contenedor de tu API Java 25
  api:
    build: .
    container_name: java_api
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - base-datos # Espera a que la base de datos inicie primero
    environment:
      # Spring leerá estas variables automáticamente si configuraste tu application.properties
      SPRING_DATASOURCE_URL: jdbc:mariadb://base-datos:3306/techstore
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Anubis@68
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

volumes:
  mariadb_data: # Define el volumen persistente para que no se borren tus datos