# Configuración de Spring Boot - Tienda Tech

# Servidor
server.port=8099
server.servlet.context-path=/

# Base de datos MariaDB
spring.datasource.url=jdbc:mariadb://localhost:3306/techstore
spring.datasource.username=root
# spring.datasource.password=Anubis@68
spring.datasource.password=
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

# Thymeleaf
spring.thymeleaf.mode=HTML
spring.thymeleaf.encoding=UTF-8
spring.thymeleaf.cache=false

# Logging
logging.level.root=INFO
logging.level.com.miapp=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate.SQL=DEBUG
